[tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "semver"
version_provider = "cargo"
tag_format = "v$version"
update_changelog_on_bump = true
bump_message = "chore(release): bump version $current_version to $new_version"
annotated_tag = true
ignored_tag_patterns = ["latest"]
